language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36-devel
  - python: 3.6
    env: TOXENV=py36
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5
    env: TOXENV=py35
  - python: 3.4
    env: TOXENV=py34
  - python: 3.3
    env: TOXENV=py33
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=py27-devel
  - python: 2.6
    env: TOXENV=py26
before_install:
    - sudo add-apt-repository ppa:chris-lea/libsodium -y 
    - echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list > /dev/null
    - echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list > /dev/null
    - sudo apt-get update && sudo apt-get install libsodium-dev
install: pip install tox
script: tox
notifications:
    email: false
